---
- name: install Python
  become: yes
  apt:
    name: python3-pip
    update_cache: yes
    state: latest

- name: Create Directory
  file:
    path: ./basic-http-server
    state: directory

- name: install Apache2
  become: yes
  apt:
    name: apache2
    update_cache: yes
    state: latest

